version: '3.4'
services:
  httpd:
    image: nginx:1.19-alpine
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "92:80"

  php-fpm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "192:80"
